### ISSUE TITLE
Highlight problem in file_rec

### ISSUE THREAD

**Issue by pocari** [Shougo/denite.nvim#138]
# Problems summary
Highlights of matched candidates is not working on two characters upper in `Denite file_rec`
(it is working in `Denite grep`)

## Provide a minimal init.vim with less than 50 lines (Required!)

test_vimrc

```vim
language message C

let s:dein_dir = expand('~/.cache/dein2')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
  if !isdirectory(s:dein_repo_dir)
    execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
  endif
  execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')
endif

call dein#begin(s:dein_dir)

call dein#add('Shougo/denite.nvim')

call dein#end()
call dein#save_state()

if dein#check_install()
  call dein#install()
endif
```

## The reproduce ways from neovim starting (Required!)

1. current dir files

```
[~/tmp]
% ls
abc.txt     axyz.txt    test_vimrc
```

2.  launch nvim

```
nvim -u test_vimrc
```

3. exec `Denite file_rec`

`:Denite file_rec`

## Screen shot 

After `:Denite file_rec` is executed it looks like this.
<img width="198" alt="2016-12-26 10 56 23" src="https://cloud.githubusercontent.com/assets/1496543/21473890/e4aa7286-cb5a-11e6-9840-a29e61dd31f5.png">

And I input `a` character, highlight is working.
<img width="193" alt="2016-12-26 10 56 36" src="https://cloud.githubusercontent.com/assets/1496543/21473895/f741cafc-cb5a-11e6-9d94-931b328496b8.png">

But  after I input `b` as a second character, the highlight disappeared(and Narrowing is working normally.) 
<img width="193" alt="2016-12-26 10 56 44" src="https://cloud.githubusercontent.com/assets/1496543/21473914/2d8deaf0-cb5b-11e6-91a5-d1446d87732d.png">

**Comment by rafi** [comment]
The culprit is [43d123c](https://github.com/Shougo/denite.nvim/commit/43d123c#diff-310bf3f97f2cc2a2fc184f4668e968b9R57), specifically the `escape_syntax` @nfnty changed.

**Comment by nfnty** [comment]
The problem is that `util.escape_syntax()` was changed to convert a string into vimscript regex literally. Offending code is [ui/default.py#L233](https://github.com/Shougo/denite.nvim/blob/master/rplugin/python3/denite/ui/default.py#L233) where python regex is being converted into vimscript regex.

This is not an easy issue to fix properly. The problem is trying to convert strings and different regex syntaxes into vimscript regex syntax. I see a few different possible fixes:
- General converter that works for most (including grep applications) types of regex syntax. Huge amount of work.
- Stripped down converter that works with a limited subset of python regex, which needs to be enforced in all filter matchers and add ability to specify regex substitute pattern when defining a grep source.
- Somehow sidestep the vim highlighting engine completely.

**Comment by Shougo** [comment]
Fixed.
