### ISSUE TITLE
asynchronously gather sources from grep

### ISSUE THREAD

**Issue by nhooyr** [Shougo/denite.nvim#144]
Right now, it looks like denite waits for grep to be finished and then lets you start searching results. fzf lets you search as results come in. denite is also very slow and laggy with large grep results.

Here is a comparison: https://asciinema.org/a/adur67892ulhpfqbmbpwxedlr

**Comment by Shougo** [comment]
Asynchronously gather sources feature is already implemented.
But the input and UI use the same thread.
It will be laggy.

**Comment by Shougo** [comment]
> Right now, it looks like denite waits for grep to be finished and then lets you start searching results.

So, this is not true.

**Comment by nhooyr** [comment]
Oh, damn. Is there any way to fix this?

**Comment by Shougo** [comment]
The UI thread and the input thread must be split.
It is @lambdalisue 's work.

**Comment by Shougo** [comment]
And you should use `matcher_cpsm` instead of others.
Other matcher is slow.

**Comment by Shougo** [comment]
Could you check the implementation @lambdalisue ?
I have not much time to solve it...

**Comment by lambdalisue** [comment]
Ok. I'm not sure if UI could be separated to a different thread safely but I'll try.

**Comment by mhahn** [comment]
@lambdalisue i would love to help make this happen if there is a direction you can point me in

**Comment by lambdalisue** [comment]
@mhahn Thanks. But I have not decide the way yet.

**Comment by HerringtonDarkholme** [comment]
I think the problem is twofold. Not necessarily denite's fault.

Denite's search uses `grep` underhood, which is more universal but slower than ag. From your [config](https://github.com/nhooyr/dotfiles/blob/master/.config/nvim/init.vim) I think you are using grep, not ag.

The second part of waiting time is probably due to [here](https://github.com/Shougo/denite.nvim/blob/master/rplugin/python3/denite/process.py#L70). If your results are fewer than 5000, denite will skip the update, until the process ends.

At least for the OP's issue, I don't think changing UI code will improve this case.

**Comment by Shougo** [comment]
OK.  I have changed the threshold to 1000.

**Comment by nhooyr** [comment]
It's still very slow.

@HerringtonDarkholme 
How can I switch to using ag?

**Comment by Shougo** [comment]
I have removed the threshold.  Please update the latest version.

**Comment by nhooyr** [comment]
@Shougo still very slow.

**Comment by Shougo** [comment]
> How can I switch to using ag?

Please read denite documentation.

> The second part of waiting time is probably due to here. If your results are fewer than 5000, denite will skip the update, until the process ends.

I have fixed the problem only.
