### ISSUE TITLE
Question: denite differences from unite?

### ISSUE THREAD

**Issue by sodiumjoe** [Shougo/denite.nvim#180]
In [this neovim-prompt issue](https://github.com/lambdalisue/neovim-prompt/issues/8), the maintainer made clear that neovim-prompt is strictly a prompt interface rather than a buffer like unite. But I think one of the best things about unite is that in the unite prompt I have the full power of vim to manipulate the prompt input.

I assume this was a deliberate decision, it seems like it might be worth noting in the README for other happy unite users like me who might be surprised and dismayed by this discovery.

Are there any other major philosophical differences between unite and denite that I should be aware of?

**Comment by Shougo** [comment]
Denite has not the buffer feature like unite.vim.
It is due to simplify the implementation and improve the performance.
Denite does not use Vim script instead of unite.vim.
Because, Vim script is very very slow.
If the plugin uses the more memory, the perfomance is very bad especially.

@lambdalisue Please add the additional information if possible.

**Comment by Shougo** [comment]
> I assume this was a deliberate decision, it seems like it might be worth noting in the README for other happy unite users like me who might be surprised and dismayed by this discovery.

The pull request of README is wellcome.

**Comment by lambdalisue** [comment]
>@lambdalisue Please add the additional information if possible.

OK. This is a summary of pros. and cons. what I think to the denite.nvim compared to unite.vim

## Pros.

- Theoretically faster while the main process is executed by python (and it is really faster 👍)
- Theoretically more stable while no other processes can be performed when denite.nvim is executed. **This is the biggest pros. of using a prompt based interface**
- Related to the above, the implementation is relatively simple than unite.vim
- Related to the above, denite.nvim has great potential to implement a new feature
- The number of Python speaker is much greater than Vim script speakers.
- Related to the above, there are a lot of useful tools to keep code simple (linter, tester, etc...)
- The unite.vim is officially obsolete, minor bugs (or even major bugs) are not fixed anymore

## Cons.

- Unite sources existing cannot be used directly (there is a `:Denite unite:xxx` but is is really limited) but I think the time will solve this issue 👍 
- Text modification features are limited while it is based on a prompt. But as I said, neovim-prompt provides a way to create a custom action and denite.nvim provides a way to create a user custom mode. So that **denite.nvim has a potential to define a Vim's operator like mode** I think (but we are not going to support it officially at least for now)
- Startup is a bit slower while denite.nvim requires to start a Python process for the first time.
- For non Neovim users: It requires a Vim compiled with `+python3`. It might be a cons. while some Linux distributions still use Python 2 as a default python.

**Comment by chemzqm** [comment]
Would custom keymapping for custom source action be implemented? I find that the biggest problem for me to use denite instead of unite.

**Comment by lambdalisue** [comment]
I may mis-understand but `<denite:do_action:{action}>` helps?
https://github.com/Shougo/denite.nvim/blob/master/doc/denite.txt#L343

**Comment by sodiumjoe** [comment]
Thanks @Shougo and @lambdalisue for the quick and thorough responses. And also thanks to both of you for the great libraries!

> The unite.vim is officially obsolete, minor bugs (or even major bugs) are not fixed anymore

This doesn't seem true, as Shougo just fixed [this bug](https://github.com/Shougo/unite.vim/issues/1215) for me a couple of weeks ago.

Forgive me for the ignorant question, as I don't know python and a quick perusal of neovim-prompt source and docs didn't make this clear, but is the selection list tied to the prompt? I.e. would it possible for denite to only use neovim-prompt while in insert mode, and use a normal buffer (like unite) when in normal mode?

In either case, I think I'll probably be able to get by with some mappings once https://github.com/lambdalisue/neovim-prompt/issues/7 is fixed.

Thanks again to both of you for the great work and for engaging with my petty complaints!

**Comment by Shougo** [comment]
> This doesn't seem true, as Shougo just fixed this bug for me a couple of weeks ago.

No, no.  I don't want to fix unite's bug anymore.
I have fixed some bugs in unite.vim.  But it is very hard to fix unite.vim bugs and I have very tired.
It is the special case.

> I.e. would it possible for denite to only use neovim-prompt while in insert mode, and use a normal buffer (like unite) when in normal mode?

I think it is cannot be.
I understand it is useful feature.
But the unite feature provides the implementation complexity and the conflict with other plugins and configurations.
I must avoid the complex in denite.nvim.

**Comment by Shougo** [comment]
@lambdalisue Thank you.  I will update the documentation.

**Comment by lambdalisue** [comment]
> I.e. would it possible for denite to only use neovim-prompt while in insert mode, and use a normal buffer (like unite) when in normal mode?

Theoretically possible but it conflicts with denite.nvim's philosophy while denite.nvim **focused simplicity** for maintenance. As I describe, using a normal buffer makes things really complicated. Shougo made denite.nvim because he learned that it becomes really critical issue at the last from the development unite.vim. So I think he will never accept such feature on denite.nvim

As I said before, if you desire, you can make a custom mode with your custom mappings with Python but there is no document for that and **we are not going to support** how or where while everything is in source code :+1: 

My suggestion is that "Get used to. It's a completely different plugin but it's worth to learn".

**Comment by sodiumjoe** [comment]
Thanks to you both for the above and beyond answers to my obnoxious questions! I can definitely understand the benefits of simplicity, and the perf advantage of denite is immediately obvious. As you say, I'll have to get used to it, and I guess I'll be picking up some python to implement a custom mode and port my (very simple) plugins over from unite. Thanks to both of you again for engaging with me and for the great libraries!
