### ISSUE TITLE
How to grep <cword>?

### ISSUE THREAD

**Issue by chenhouwu** [Shougo/denite.nvim#211]
I can grep with the following config
```
nnoremap <silent> [denite]g :<C-u>Denite grep -no-empty -buffer-name=search-buffer-denite<CR>
```
it will prompt for a pattern to grep.

But how can I grep the current word under cursor directly?
I searched the issues list but find no related one.

`DeniteCursorWord` does not work, because the <cword> is used for filter, not for the initial `grep` prompt.

**Comment by sodiumjoe** [comment]
`DeniteCursorWord` works for me like this:

```
:DeniteCursorWord grep:.
```

It does put the word under the cursor as the prompt input as well, but that doesn't seem like it should matter, since presumably all the return values would include that text as well.

```
:DeniteCursorWord grep:. -input=""
```
seems like it would do what you want, but the `input` option doesn't appear to have any effect for `DeniteCursorWord`

**Comment by Shougo** [comment]
> `DeniteCursorWord` does not work, because the is used for filter, not for the initial grep prompt.

I don't understand what you want.
`DeniteCursorWord` worksfor me.

**Comment by Shougo** [comment]
If you want to change the search word, but don't change the input.

```vim
Denite grep:::`expand('cword')`
```

> seems like it would do what you want, but the input option doesn't appear to have any effect for DeniteCursorWord

Because `DeniteCursorWord` changes `input` option.
It is the feature.

**Comment by chenhouwu** [comment]
```
Denite grep:::`expand('<cword>')`
```
works

**Comment by Shougo** [comment]
Yes, it is the right.
