### ISSUE TITLE
File paths relative to the project root

### ISSUE THREAD

**Issue by musaffa** [Shougo/denite.nvim#27]
The search results in `Denite file_rec` show absolute paths. How can we make it shorter so that the file paths are relative to the project root? By project root, I meant the directory in which vim is opened.

**Comment by okamos** [comment]
Hi.

You can make it shorter file paths below command.

```vim
:call denite#start([{'name': 'file_rec', 'args': '.'}])
```

But you have to set current directory as project root.

**Comment by musaffa** [comment]
@okamos Thanks! Can it be made default every time I call `Denite file_rec`?

**Comment by taecilla** [comment]
> But you have to set current directory as project root.

@okamos can you elaborate on that?

**Comment by Shougo** [comment]
Fixed.

**Comment by okamos** [comment]
Thanks!!

**Comment by oblitum** [comment]
I wish the same for `Denite file` and `DeniteProjectDir file`, fuzzy match with long and repeated absolute paths are not great. How to do it?

**Comment by oblitum** [comment]
I consider current `Denite file` and `DeniteProjectDir file` behavior is broken because of absolute path matching:

1. `cd ~`
2. `mkdir test`
3. `cd test`
4. `touch test`
5. `touch aaaa`
6. `nvim`
7. `:Denite file`
8. type "test"

The current working directory you started `nvim` is `~/test/`, there are two files, and from fuzzy finding "test" from **inside** that directory you expect the file `test` in there as the first result, but it's not! because what you typed is matching against the parent path `~/test/` (for no reason at all), so the first result is still `aaaa`, and you have to type something different than the obvious to match the `test` file.

**Comment by Shougo** [comment]
You can use converter_abbr_word.

```vim
call denite#custom#source('file/old', 'matchers',
      \ ['converter/abbr_word', 'matcher/fuzzy'])
```

**Comment by oblitum** [comment]
@Shougo Thanks for the tip, I just tried it but it had no effect.

**Comment by oblitum** [comment]
> @Shougo Thanks for the tip, I just tried it but it had no effect.

Correction, items are sorted differently for that test case, and `test` comes first upfront, so maybe I need to build another test. At first I thought nothing changed because I tried in a big directory and just saw the absolute paths again, so I thought it was not working.

**Comment by Shougo** [comment]
Please test the latest version of denite.nvim.
I have fixed it.

**Comment by oblitum** [comment]
@Shougo many thanks, it's much better now.
