### ISSUE TITLE
Denite configuration: why functions and not variables?

### ISSUE THREAD

**Issue by DerWeh** [Shougo/denite.nvim#272]
I have hardly any idea, how vim/nvim and its plug-ins work under the hood, but I was curious if there is a reason why you use functions instead of variable to configure `Denite`?

Personally I would find variables more helpful to keep my `init.vim` clean, because I can just put them in `ftplugin/denite.vim`. Functions however are only executed after starting the `Denite` buffer (at least I think so, please correct me if I am wrong), so they would only work the second time I use `Denite`.

**Comment by Shougo** [comment]
> but I was curious if there is a reason why you use functions instead of variable to configure Denite?

It is expected.  Because, if denite uses the raw level variables, denite cannot implement alias feature correctly.
https://github.com/Shougo/denite.nvim/issues/258

Denite can do that.  Other plugins cannot.

I think to implement general features is better than to implement easy to use features.

> Functions however are only executed after starting the Denite buffer (at least I think so, please correct me if I am wrong), so they would only work the second time I use Denite.

For example, dein.vim has the feature.  `on_source` hook is for it.
